### PR TITLE
Reset state of SinglyLinkedList after accesing a key on HashTable

### PR DESCRIPTION
**Pull request by brunops**
- HashTable#[] was maintaining current_node state of its list, which
  caused the next access to the same hashed_key to return nil
- Added test for it
- Couldn't keep a one liner.. My ruby skillz are kinda fading away :P

### CODE REVIEW

**Comment by edshadi** [comment]
@brunops  actually don't worry about the branch, realized you did it from a fork, so you did the awesome thing. Just update your fork with the latest (I won't mess with the structure again) and resubmit the request please and I'll merge it.

**Comment by brunops** [comment]
I have rebased my change on top of your updates and force pushed... #shameonme  hahaha Not sure if the pull request is automatically updated though...

**Comment by edshadi** [comment]
all merged!
On March 5, 2014 at 5:01:53 PM, Bruno Sanches (notifications@github.com) wrote:

I have rebased my change on top of your updates and force pushed... #shameonme hahaha Not sure if the pull request is automatically updated though...

**Comment by brunops** [comment]
I was thinking about it and maybe the list should have a #find method, then there wouldn't be the need to use .value.value or reset it, current_node could actually be private

**Comment by edshadi** [comment]
I totally agree, I hate how we're dipping inside the list. There is already a #find on the linked list, which we could use.

**Comment by brunops** [comment]
Didn't see it. But yes, you're right. It doesn't seem to reset the list at the end either. Maybe removing the the current_node instance variable completely and not having any state to depend on is better. So we can get rid of the reset method too, and just start at the head all the time.

**Comment by edshadi** [comment]
We have to modify the find a bit since we only have the key and not the entry object. We can make the find smarter so that way the linked list implementation is not too tightly coupled with the HashTable. Keeping the state in @current_node is getting messy for sure but it serves as a moving needle for the next_node and prev_node (in doubly).

**Comment by brunops** [comment]
Couldn't prev_node and next_node only be properties of Node? I'm not sure if DoublyLinkedList needs these methods, the needles can be only head and tail

**Comment by edshadi** [comment]
Node does have next_node and prev_node, the list.next_node basically uses that under the hood. It was my attempt to make traversing the list easier, but so far it proved noisy. I’ll remove current_node, next_node and prev_node from the linked lists and hash table. Still determined to come up with a nicer way to traverse though, oh well. I’m also implementing all this in Javascript as well, I’ll share soon.
On March 5, 2014 at 6:36:43 PM, Bruno Sanches (notifications@github.com) wrote:

Couldn't prev_node and next_node only be properties of Node? I'm not sure if DoublyLinkedList needs these methods, the needles can be only head and tail

**Comment by edshadi** [comment]
duh, enumerable to the rescue! implemented each method and included enumerable in linked lists. No more pointers and no more reset. I cleaned the code quite a bit, let me know what you think.
On March 5, 2014 at 9:16:34 PM, Ed Shadi (edshadi@gmail.com) wrote:

Node does have next_node and prev_node, the list.next_node basically uses that under the hood. It was my attempt to make traversing the list easier, but so far it proved noisy. I’ll remove current_node, next_node and prev_node from the linked lists and hash table. Still determined to come up with a nicer way to traverse though, oh well. I’m also implementing all this in Javascript as well, I’ll share soon.
On March 5, 2014 at 6:36:43 PM, Bruno Sanches (notifications@github.com) wrote:

Couldn't prev_node and next_node only be properties of Node? I'm not sure if DoublyLinkedList needs these methods, the needles can be only head and tail

**Comment by brunops** [comment]
Enumerable! hahaha that's really smart, code looks way better now :+1:

**Pull request merged**
